name: JAX Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      KERAS_BACKEND: jax

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build pytest keras jax jaxlib packaging

      - name: Run tests
        run: pytest tests
