name: Test

on:
  release:
    types: [published]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build pytest pytest-env keras tensorflow packaging

      - name: Run tests
        run: pytest tests/numpy_test.py
